auto: true

#markdown: rdiscount
highlighter: 'pygments'
#paginate: 8
permalink: /:title

title: My Blog
url: http://zuoqx.github.io
feed: /atom.xml
author_info: <a href="http://zuoqx.github.io/">Zuoqx</a>
