auto: true

highlighter: rouge
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
#paginate: 8
permalink: /:title

title: 天道酬勤
url: http://zuoqx.github.io
feed: /atom.xml
author_info: <a href="http://zuoqx.github.io/">Zuoqx</a>
disqus_username: qxzuoblogdisqus